title: My awesome title
author: pear25
email: piersonlimas12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
wwooowwowowwo

# social links
twitter_username: i dont have # DO NOT include the @ character, or else the build will fail!
github_username:  pear25 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

